import type { Metadata } from 'next';
import './globals.css';
import { ModalProvider } from '@/providers/ModalContext';
import { geistMono, geistSans } from './styles/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-zinc-50 dark:bg-black">
        <ModalProvider>
          {children}
        </ModalProvider>

        <div id="modal-container"></div>
      </body>
    </html>
  );
}
